
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "{{ .Release.Name  }}-ingress"
  labels:
    appName: {{ .Release.Name  }}
spec:
  rules: 
  - http:
      paths:
        - path: "/"
          backend:
            serviceName: "{{ .Release.Name  }}-service"
            servicePort: {{ .Values.service.port }}
